language: erlang
install: true
before_script:
  - make setup-rebar3
  - make setup-hexpm
env:
  - REBAR_BUILD=github
  - REBAR_BUILD=gitlab
  - REBAR_BUILD=hexpm
script:
  - make travis
  #- make check-hexpm # XXX disabled due to Hex.pm failing on R15
otp_release:
  - 19.2
  - 18.3
  - 17.5
  - R16B03-1
