name: ci/cd

on:
  push:
    branches: [ master, 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: [ master, 'release/**', 'task/**', 'feature/**', 'epic/**']

jobs:

  build:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [21, 22, 23, 24]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.15'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Proper Tests
      run: rebar3 proper --regressions
    - name: Run Tests
      run: rebar3 ct -c
    - name: Test Coverage
      run: rebar3 do proper -c, cover -v --min_coverage=60
    - name: Generate Docs
      run: rebar3 edoc
